-- AlterTable
ALTER TABLE `User` ADD COLUMN `branch` VARCHAR(191) NULL,
    ADD COLUMN `country` VARCHAR(191) NULL,
    ADD COLUMN `phoneNumber` VARCHAR(191) NULL,
    ADD COLUMN `state` VARCHAR(191) NULL;
